### ISSUE TITLE
Value was either to large or too small for an init32.

### ISSUE THREAD

**Issue by PmbrugPurnjayDEV** [jean-knapp/xblah-modding-tool-public#3]
I keep getting this problem here is the details:

**Comment by PmbrugPurnjayDEV** [comment]
the error:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at xblah_modding_lib.Game.GetAppId() in D:\Files\Development\CS\xblah-modding-tool\xblah-modding-lib\Game.cs:line 95
   at xblah_modding_lib.Launcher.LoadGames() in D:\Files\Development\CS\xblah-modding-tool\xblah-modding-lib\Launcher.cs:line 70
   at xblah_modding_tool.MainForm.updateToolsGames()
   at xblah_modding_tool.MainForm.Form_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.DForm.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
XBLAH's Modding Tool
    Assembly Version: 1.14.5.0
    Win32 Version: 1.14.5.0
    CodeBase: file:///C:/Users/brug/Desktop/xblah/XBLAH's%20Modding%20Tool.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4590.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
DevExpress.Utils.v21.2
    Assembly Version: 21.2.6.0
    Win32 Version: 21.2.6.0
    CodeBase: file:///C:/Users/brug/Desktop/xblah/bin/DevExpress.Utils.v21.2.DLL
----------------------------------------
DevExpress.Data.v21.2
    Assembly Version: 21.2.6.0
    Win32 Version: 21.2.6.0
    CodeBase: file:///C:/Users/brug/Desktop/xblah/bin/DevExpress.Data.v21.2.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
DevExpress.XtraTreeList.v21.2
    Assembly Version: 21.2.6.0
    Win32 Version: 21.2.6.0
    CodeBase: file:///C:/Users/brug/Desktop/xblah/bin/DevExpress.XtraTreeList.v21.2.DLL
----------------------------------------
DevExpress.Data.Desktop.v21.2
    Assembly Version: 21.2.6.0
    Win32 Version: 21.2.6.0
    CodeBase: file:///C:/Users/brug/Desktop/xblah/bin/DevExpress.Data.Desktop.v21.2.DLL
----------------------------------------
DevExpress.XtraBars.v21.2
    Assembly Version: 21.2.6.0
    Win32 Version: 21.2.6.0
    CodeBase: file:///C:/Users/brug/Desktop/xblah/bin/DevExpress.XtraBars.v21.2.DLL
----------------------------------------
DevExpress.XtraEditors.v21.2
    Assembly Version: 21.2.6.0
    Win32 Version: 21.2.6.0
    CodeBase: file:///C:/Users/brug/Desktop/xblah/bin/DevExpress.XtraEditors.v21.2.DLL
----------------------------------------
DevExpress.Images.v21.2
    Assembly Version: 21.2.6.0
    Win32 Version: 21.2.6.0
    CodeBase: file:///C:/Users/brug/Desktop/xblah/bin/DevExpress.Images.v21.2.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4584.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
CefSharp.WinForms
    Assembly Version: 94.4.110.0
    Win32 Version: 94.4.110.0
    CodeBase: file:///C:/Users/brug/Desktop/xblah/bin/CefSharp.WinForms.DLL
----------------------------------------
CefSharp.Core
    Assembly Version: 94.4.110.0
    Win32 Version: 94.4.110.0
    CodeBase: file:///C:/Users/brug/Desktop/xblah/bin/CefSharp.Core.DLL
----------------------------------------
CefSharp
    Assembly Version: 94.4.110.0
    Win32 Version: 94.4.110.0
    CodeBase: file:///C:/Users/brug/Desktop/xblah/bin/CefSharp.DLL
----------------------------------------
CefSharp.Core.Runtime
    Assembly Version: 94.4.110.0
    Win32 Version: 94.4.110
    CodeBase: file:///C:/Users/brug/Desktop/xblah/bin/CefSharp.Core.Runtime.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Users/brug/Desktop/xblah/bin/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Data.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Linq.dll
----------------------------------------
xblah-modding-lib
    Assembly Version: 1.14.2.0
    Win32 Version: 1.14.2.0
    CodeBase: file:///C:/Users/brug/Desktop/xblah/bin/xblah-modding-lib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
