### ISSUE TITLE
Material editor reports an error from importing image

### ISSUE THREAD

**Issue by Deliveredmean42** [jean-knapp/xblah-modding-tool-public#5]
The built-in material editor seems to just not work properly when attempting to import a standard image file.

Message:
The system cannot find the file specified

Stack Trace:
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at xblah_modding_lib.Materials.VTF.FromBitmap(Bitmap bitmap, Launcher launcher, String[] properties)
   at xblah_modding_lib.Materials.VTF.FromBitmap(Bitmap bitmap, Launcher launcher)
   at xblah_modding_tool.MaterialEditor.ImportTexture(String tag, ShaderInterface tabInterface)
   at xblah_modding_tool.Materials.ShaderTabs.VertexLitGenericTab.pictureEditPopup_ItemClick(Object sender, ItemClickEventArgs e)
   at DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)
   at DevExpress.XtraBars.Controls.CustomLinksControl.OnMouseUp(MouseEventArgs e)
   at DevExpress.XtraBars.Controls.CustomPopupBarControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraBars.Controls.CustomControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Operational System:Windows 10 Enterprise

Tool Version:1.16.1.0

**Comment by vaqxai** [comment]
I have that error too

**Comment by jean-knapp** [comment]
This has been fixed in v2.1. Now the vtfs are compiled natively instead of relying on vtex.exe.
