### ISSUE TITLE
"An item with the same key has already been added." after signing in/opening tool

### ISSUE THREAD

**Issue by XX99-99** [jean-knapp/xblah-modding-tool-public#8]
After signing into or opening the tool, I was getting this error. This started happening after I updated to the most recent version (1.17.2) as I recall it; redownloading the tool did not fix the issue. This prevented me from using the tool, as it got stuck on "Loading games..."

This issue is actually easy to fix on the end user's part, and I believe it is caused by having duplicate games/mods on multiple hard drives; for example, having an install of CS:GO on a C:/ drive and also on a D:/ drive. While the easiest fix here for the end user is to simply rename SteamLibrary or to uninstall CS:GO on the D:/ drive in this scenario, I think it's worth mentioning here, as it prevented me from using the app entirely for a while.

Begin error report:

Message:
An item with the same key has already been added.

Stack Trace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at xblah_modding_lib.Launcher.LoadGames()
   at xblah_modding_tool.MainForm.updateToolsGames()
   at xblah_modding_tool.MainForm.Form_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.DForm.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Operational System:Windows 10 Home

Tool Version:1.17.2.0

**Comment by jean-knapp** [comment]
Check if you don`t have duplicates of the same game.
